### ISSUE TITLE
How to finetune? and how to train with images of different dimensions?

### ISSUE THREAD

**Issue by kalyani7195** [aliyun/NeWCRFs#22]
Firstly, congratulations on your publication and thanks a lot for open sourcing the code base. great work !!!
Hi! I have a couple of questions:
1. Can you please guide me on how to fine-tune a pretrained model on a similar dataset having a slightly different distribution? I can see the option for loading a pretrained backbone, but not for fine-tuning the model with pretrained weights. 
2. I get weird errors like the following when I try to train on images with different dimensions -- other than (640, 480) Do you have any suggestions on how to tackle this issue?

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/gscratch/sciencehub/kmarathe/models/NeWCRFs_Conveyor/newcrfs/train.py", line 321, in main_worker
    depth_est = model(image)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/NeWCRFs_Conveyor/newcrfs/networks/NewCRFDepth.py", line 133, in forward
    e2 = self.crf2(feats[2], e3)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/NeWCRFs_Conveyor/newcrfs/networks/newcrf_layers.py", line 428, in forward
    x_out, H, W, x, Wh, Ww = self.crf_layer(x, v, Wh, Ww)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/NeWCRFs_Conveyor/newcrfs/networks/newcrf_layers.py", line 357, in forward
    x = blk(x, v, attn_mask)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/NeWCRFs_Conveyor/newcrfs/networks/newcrf_layers.py", line 232, in forward
    v_windows = window_partition(shifted_v, self.window_size)  # nW*B, window_size, window_size, C
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/NeWCRFs_Conveyor/newcrfs/networks/newcrf_layers.py", line 40, in window_partition
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
RuntimeError: shape '[2, 5, 7, 6, 7, 512]' is invalid for input of size 1541120

Any help would be greatly appreciated. 
Thank you! Kalyani

**Comment by weihaosky** [comment]
1. Load the trained model, decrease the learning rate, and then do the training.
2. You should debug yourself. Sometimes this is related to the resolution. The resolution (H, W) should be divisible by 32.

**Comment by kalyani7195** [comment]
Thanks for your reply! I will try that out.
And yes, it's all about whether the w and h are divisible by 32 or not. Thanks for your help, really appreciate it.

**Comment by VanHoo** [comment]
Hello, what dataset did you use for the fine-tuning? 
Thank you
